server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: HERO
  main:
    banner-mode: off

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
