server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: DISCOVERY
  main:
    banner-mode: off
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  server:
    expected-client-renewal-interval-seconds: 15
